/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-09-24 10:31:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.toyodo.model.Invoice;
import com.toyodo.service.impl.EmployeeServiceImpl;
import com.toyodo.service.EmployeeService;
import java.util.*;
import java.io.*;
import com.toyodo.utils.*;
import com.toyodo.notification.*;
import com.toyodo.model.Employee;
import com.toyodo.model.Order;
import com.toyodo.model.Products;
import com.toyodo.model.Quote;

public final class employeeOrderList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/modal/quote.jsp", Long.valueOf(1632253650600L));
    _jspx_dependants.put("/WEB-INF/nav/dashboardNav.html", Long.valueOf(1632005445290L));
    _jspx_dependants.put("/WEB-INF/nav/sidebarNav.html", Long.valueOf(1632208355155L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.toyodo.notification");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("com.toyodo.utils");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.toyodo.model.Employee");
    _jspx_imports_classes.add("com.toyodo.model.Invoice");
    _jspx_imports_classes.add("com.toyodo.model.Quote");
    _jspx_imports_classes.add("com.toyodo.model.Order");
    _jspx_imports_classes.add("com.toyodo.model.Products");
    _jspx_imports_classes.add("com.toyodo.service.impl.EmployeeServiceImpl");
    _jspx_imports_classes.add("com.toyodo.service.EmployeeService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>List of Orders</title>\r\n");
      out.write("<link href=\"/ToYoDo/CSS/layout.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		HttpSession httpSession = request.getSession(false);
		String employeeID = (String) httpSession.getAttribute("loginID");
		System.out.println(employeeID);
		if (employeeID == null || httpSession.isNew()) {
			RequestDispatcher rd = request.getRequestDispatcher("/JSP/index.jsp");
			request.setAttribute("unauthorised_msg", Notify.UNAUTHORISED);
			rd.forward(request, response);
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("\t<a class=\"navbar-brand\" href=\"#\">ToYoDo - Order Management\r\n");
      out.write("\t\tDashboard</a>\r\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\taria-label=\"Toggle navigation\"></button>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t<span class=\"navbar-text\">Welcome ");
      out.print(employeeID );
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav \">\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/ToYoDo/Logout\">Logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"sidebar-left\">\r\n");
      out.write("\t\t");

			EmployeeService employeeService = new EmployeeServiceImpl();
		
      out.write("\r\n");
      out.write("\t\t");
      out.write("<div class=\"d-flex flex-column\">\r\n");
      out.write("  <div class=\"p-2\"><a href=\"/ToYoDo/JSP/employeeOrderList.jsp\">\r\n");
      out.write("  \t<i class=\"fas fa-list\"></i><strong class=\"nav-link d-none d-lg-inline\"> List of Orders</strong></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"p-2\"><a href=\"/ToYoDo/JSP/employeeQuote.jsp\">\r\n");
      out.write("  \t<i class=\"fas fa-plus\"></i><strong class=\"nav-link d-none d-lg-inline\"> Create New Quote</strong></a>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"p-2\"><a href=\"\" data-toggle=\"modal\" data-target=\"#viewQuoteModal\">\r\n");
      out.write("  \t<i class=\"fas fa-eye\"></i><strong class=\"nav-link d-none d-lg-inline\"> View Quote</strong></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"p-2\"><a href=\"\">\r\n");
      out.write("  \t<i class=\"fas fa-file-import\"></i><strong class=\"nav-link d-none d-lg-inline\"> Import Products</strong></a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("<!-- modal to view quote -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"viewQuoteModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\taria-labelledby=\"quoteModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog modal-dialog-centered modal-lg\"\r\n");
      out.write("\t\trole=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h5 class=\"modal-title\" id=\"quoteModalLongTitle\">Quote</h5>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-striped table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">Order Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">Customer GST No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">Shipping Address</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">Phone Number</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">Total Order Value</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\">Status</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								List<Quote> viewQuote = employeeService.viewQuote();
								for (Quote quote : viewQuote) {
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(quote.getOrder_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(quote.getCustomer_gst_no());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(quote.getCustomer_shipping_address());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(quote.getCustomer_phone_number());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&#8377; ");
      out.print(quote.getTotal_order_value());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(quote.getStatus());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<h3>Orders</h3>\r\n");
      out.write("\t\t<form method=\"POST\" onsubmit=\"return main()\" action=\"/ToYoDo/EmployeeController?action=invoice\">\r\n");
      out.write("\t\t\t<table class=\"table table-striped table-responsive\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">Order ID</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">Order Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">Customer ID/Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">Customer Shipping Address</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">List of Products</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">Total Order Value</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">Status</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">Invoice</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");

						List<Order> listOrder = employeeService.listOrder();
						for (Order order : listOrder) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(order.getOrderID());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"date\" name=\"orderDate\" value=\"");
      out.print(order.getOrderDate());
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(order.getCustomerID());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(order.getCustomerShippingAddress());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(order.getListOfProducts());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>&#8377; ");
      out.print(order.getTotalOrderValue());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(order.getStatus());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<th><button class=\"btn btn-info btn-sm\" name=\"orderDatetime\" value=\"");
      out.print(order.getOrderDatetime());
      out.write("\"><i class=\"fas fa-file-invoice\"></i></button></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\tCopyright &copy; 2021 ToYoDo<br /> All rights reserved. Powered by JAVATAR\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
